export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const ADD_USERS_REQUEST = 'ADD_USERS_REQUEST';
export const ADD_USERS_SUCCESS = 'ADD_USERS_SUCCESS';
export const ADD_USERS_FAIL = 'ADD_USERS_FAIL';

export const REMOVE_USERS_REQUEST = 'REMOVE_USERS_REQUEST';
export const REMOVE_USERS_SUCCESS = 'REMOVE_USERS_SUCCESS';
export const REMOVE_USERS_FAIL = 'REMOVE_USERS_FAIL';


export const EDIT_USERS_REQUEST = 'EDIT_USERS_REQUEST';
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS';
export const EDIT_USERS_FAIL = 'EDIT_USERS_FAIL';
